<?php
// This file generated by Propel 1.5.6 convert-conf target
return array (
  'BaseSession' => 'colony/om/BaseSession.php',
  'BaseSessionPeer' => 'colony/om/BaseSessionPeer.php',
  'BaseSessionQuery' => 'colony/om/BaseSessionQuery.php',
  'Session' => 'colony/Session.php',
  'SessionPeer' => 'colony/SessionPeer.php',
  'SessionQuery' => 'colony/SessionQuery.php',
  'SessionTableMap' => 'colony/map/SessionTableMap.php',
);