<?php
// This file generated by Propel 1.5.6 convert-conf target
return array (
  'BaseEvent' => 'colony/om/BaseEvent.php',
  'BaseEventPeer' => 'colony/om/BaseEventPeer.php',
  'BaseEventQuery' => 'colony/om/BaseEventQuery.php',
  'BaseSession' => 'colony/om/BaseSession.php',
  'BaseSessionPeer' => 'colony/om/BaseSessionPeer.php',
  'BaseSessionQuery' => 'colony/om/BaseSessionQuery.php',
  'Event' => 'colony/Event.php',
  'EventPeer' => 'colony/EventPeer.php',
  'EventQuery' => 'colony/EventQuery.php',
  'EventTableMap' => 'colony/map/EventTableMap.php',
  'Session' => 'colony/Session.php',
  'SessionPeer' => 'colony/SessionPeer.php',
  'SessionQuery' => 'colony/SessionQuery.php',
  'SessionTableMap' => 'colony/map/SessionTableMap.php',
);